### ISSUE TITLE
Remove "(Firefox XX+)" from cipherSuite.label and protocol.label

### ISSUE THREAD

**Issue by Cai0407** [gavinhungry/cipherfox#30]
Now, cipherSuite.label and protocol.label in pref.dtd have annotations about available Firefox version.

    <!ENTITY cipherSuite.label "Full Cipher Suite (Firefox 25+)">
    <!ENTITY protocol.label    "Protocol Version (Firefox 36+)">

I think it is good time to remove these annotations because Firefox 31 ESR has been EOLed and support for Pale Moon has been added.

other than ja-JP;

    <!ENTITY cipherSuite.label "Full Cipher Suite">
    <!ENTITY protocol.label    "Protocol Version">
ja-JP;

    <!ENTITY cipherSuite.label "完全な Cipher Suite">
    <!ENTITY protocol.label    "プロトコルバージョン">

**Comment by gavinhungry** [comment]
@Cai0407, while it is true that Firefox is now no longer the only explicitly supported platform for CipherFox, according to the [latest stats](https://addons.mozilla.org/en-us/firefox/addon/cipherfox/statistics/usage/applications/?last=30), over 10% of CipherFox users are still on Firefox < 36, which would at least prevent them from using `$PROTOCOL`.

Options:
  1. Do nothing
  2. Bump `minVersion` Firefox to 36.
  3. Remove support for `$PROTOCOL` and `$CIPHERSUITE` from incompatible versions

I suppose (2) is the right answer anyway, since ESR is up to 38, and this is a security-focused add-on - why bother with users that can't be bothered to keep their browser up-to-date?

**Comment by gavinhungry** [comment]
Fixed by 21ae29c832b19c53bcaba1d1e8f583c52e1a4fd1 d10f27c01289933c9a75cb3482219e199b4380e3

**Comment by Cai0407** [comment]
Thanks for quick fix!

**Comment by gavinhungry** [comment]
@Cai0407 - I should also note that both Pale Moon and SeaMonkey support `$PROTOCOL` and `$CIPHERSUITE`.
