### ISSUE TITLE
Error thrown with cipherfox 4.1.1 in Pale Moon 27.5.*

### ISSUE THREAD

**Issue by wolfbeast** [gavinhungry/cipherfox#50]
Cipherfox 4.1.1 throws the following error when installed in Pale Moon 27.5.*:

```
00:10:04.963 [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) 
[nsIStringBundle.GetStringFromName]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  
location: "JS frame :: chrome://cipherfox/content/cipherfox.js :: formatLabel :: line 296" 
data: no]
```

This seems to be in the case statement where hash types are determined, assuming strings are available with the same names as in Firefox.
With this error thrown, the extension fails to work entirely.

**Comment by wolfbeast** [comment]
If I wrap the switch statement in a `try()/catch()`, it works, although it displays "?" for the certificate hash in that case (of course).

**Comment by gavinhungry** [comment]
This looks to be because Pale Moon does not have support for the following certificate signature algorithms (or at least, they don't appear in `pipnss.properties`):

    CertDumpAnsiX962ECDsaSignatureWithSha224
    CertDumpAnsiX962ECDsaSignatureWithSha256
    CertDumpAnsiX962ECDsaSignatureWithSha384

My mistake was not realizing that calling `StringBundle@GetStringFromName` with a string key that does not exist in the bundle would throw an error.  I will wrap all of these calls in a helper function that catches this.  You will still see the `?` placeholder.

**Comment by wolfbeast** [comment]
We don't have the strings in the .properties file because we don't pretty-print the names of ECDSA with SHA-2 algorithms in Certificate Viewer. Yet, anyway; seems like a good enhancement, so it'll help your extension out in turn too.
